version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'user-service'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'nish@123'
      MYSQL_ROOT_PASSWORD: '@Password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - /home/nishant/data:/var/lib/mysql
